### ISSUE TITLE
Checkpoint #1 ready!

### ISSUE THREAD

**Issue by redfoxanna** [redfoxanna/diamond-poems#1]
Hi @pawaitemadisoncollege! I have my checkpoint #1 for diamond-poems for you to look at!

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna! 

Thanks for sharing your indie project checkpoint 1! You are off to a very solid start: I see some code already and it feels like you have some really good energy around this fun project!

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it. 

- [x] I appreciated the link to the wikipedia article! I was very excited to see your examples, but the two image links seem broken. Ideally the images should show right in the readme.md.
- [x] You have quite a lot listed under independent research topics - don't feel obligated to have so many just because I had a longer list in the demo repo. It may turn out that areas of interest will crop up more organically and you can add them if you have time to explore them. 

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example, full CRUD and an api that adds good value to your application. That said, sometimes I am too optimistic/ambitious, so let's both keep an eye on how things progress and what, if anything needs to be delayed to V2. 

These appear to be well-thought-out - no nitpicks. 

One question - will the uploaded images be stored somewhere, or do they only stick around until they are OCR'd?  Asking because you'll want to consider where/how to store them if they do need to be persisted. 

**Project plan**

You did a thorough job laying out the high-level tasks over the course of the semester. If this plan provides you with enough detail to get the work done, go with it. Some students find it helpful to break down larger tasks into smaller parts - find what works for you. Your flow and brainstorm docs look really helpful, so maybe those smaller task-things are handled there! 

- [ ] I noticed you mentioned researching and implementing user auth - we will be doing auth in week 7 with Cognito. My hope is the exercise that week gives you what you need to handle this part. 
- [ ] The OCR portion - we will cover consuming services in week 8, so you *could* push this back, or know that if you do want to do this in week 3-6, that you can poke ahead to week 8 materials for more info on how to do this.
- [x] Some formatting looks a little off in the markdown when viewed in GitHub around week 8-9 to the end. 

**Screen design**

These do a good job capturing MVP and should help guide your development.

- [ ] This might have been my connection/my browser, but I wasn't able to view all of the screens in GitHub and had to download them. No biggie, just pointing it out.

**Reflection statements/Time Log**

Great work consistently tracking! 

**Other**

- [ ] I noticed some property/config files which could contain information like usernames, passwords, etc. It would be a good idea to remove these from GitHub and add them to .gitignore. If you aren't able to find the details on how to do this, please post in slack as I'm sure other will run into this too!

**Comment by redfoxanna** [comment]
Hi @pawaitemadisoncollege! I have added a few example Diamond Poems to the README if you would like to see some examples! One thing to note--Now that I have taken the time to really read through the paper examples from game nights, I am realizing that quite a fair amount contain swearing or dark subjects. *Pause here to read last two examples provided, if you have not already* What is your opinion on how to handle these? I'm all for freedom of speech but I do understand this project is for academic purposes 😂

Also, I think I got the property/config files you were talking about removed from my repository. Thanks for catching that!!

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna. This is a _very_ good question. 

Personally, most language or subjects do not offend _me_. I can imagine playing this with my friends and I'm pretty sure we'd produce similar stuff.  

So now I'm taking off my baseball cap and putting on my "teacher/advisor" hat (whatever that looks like). Perhaps the litmus test is this: if this project is part of your portfolio, and prospective employers are looking at it, how might some language affect them and their first impressions of you? I can imagine a number of answers to this.

I wonder if there is opportunity here for a user story related to language. Based on a user's settings, could a certain words/language be redacted? I don't want to add more to your scope necessarily, just tossing it out there to see how you feel about it. 

As I am writing this, perhaps another idea is some sort of "warning" this example includes explicit language?? Trigger warnings..?
